config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  match '/thank_you' => "static#thank_you"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

# Comment this out when running rake db:migrate for the first time
  mount CatarseWepay::Engine => "/", as: "catarse_wepay"

  # Non production routes
  if Rails.env.development?
    resources :emails, only: [ :index ]
  end


  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/guidelines',            to: 'static#guidelines',          as: :guidelines
  get "/guidelines_tips",       to: "static#guidelines_tips",     as: :guidelines_tips
  get "/guidelines_backers",    to: "static#guidelines_backers",  as: :guidelines_backers
  get "/guidelines_start",      to: "static#guidelines_start",    as: :guidelines_start
  get "/referrals",             to: "static#referrals",           as: :referrals
  get "/foundation",            to: "static#foundation",          as: :foundation

  get "/about",                 to: "static#about",               as: :about
  get "/military",              to: "static#about_military",      as: :about_military
  get "/firefighters",          to: "static#about_firefighters",  as: :about_firefighters
  get "/first_responders",      to: "static#about_first_responders",as: :about_first_responders
  get "/community",             to: "static#about_community",      as: :about_community
  get "/entrepreneurial",       to: "static#about_entrepreneurial",as: :about_entrepreneurial
  get "/creative",              to: "static#about_creative",       as: :about_creative

  get "/departments",           to: "static#about_departments",    as: :about_departments
  get "/organizations",         to: "static#about_organizations",  as: :about_organizations
  get "/families",              to: "static#about_families",       as: :about_families

  match "/explore" => "explore#index", as: :explore
  match "/explore#:quick" => "explore#index", as: :explore_quick
  match "/credits" => "credits#index", as: :credits

  match "/reward/:id" => "rewards#show", as: :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ] do
      member do
        post 'sort'
      end
    end
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'video'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, only: [:index] do
      member do
        match :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end
  # match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/mudancadelogin" => "users#set_email", as: :set_email_users
  match "/:permalink" => "projects#show", as: :project_by_slug

  # Root path
  root to: 'projects#index'

end

app/controllers/adm/backers_controller.rb
class Adm::BackersController < Adm::BaseController
  menu I18n.t("adm.backers.index.menu") => Rails.application.routes.url_helpers.adm_backers_path
  has_scope :by_user_id, :by_key, :user_name_contains, :project_name_contains, :confirmed, :credits, :requested_refund, :refunded,
    :by_state, :by_value
  has_scope :between_values, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :pending_to_refund do |controller, scope, value|
    if value.present?
      scope.pending_to_refund 
    else
      scope
    end
  end
  before_filter :set_title

  def self.backer_actions
    %w[confirm pendent refund hide cancel].each do |action|
      define_method action do
        resource.send(action)
        flash[:notice] = I18n.t("adm.backers.messages.successful.#{action}")
        redirect_to adm_backers_path
      end
    end
  end
  backer_actions

  def change_reward
    resource.change_reward! params[:reward_id]
    flash[:notice] = I18n.t('adm.backers.messages.successful.change_reward')
    redirect_to adm_backers_path
  end

  protected
  def set_title
    @title = t("adm.backers.index.title")
  end

  def collection
    @backers = end_of_association_chain.order("backers.created_at DESC").page(params[:page])
  end
end

app/controllers/adm/base_controller.rb
class Adm::BaseController < ApplicationController
  inherit_resources
  before_filter do
    authorize! :manage, resource_class  
  end

  @@menu_items = {}
  cattr_accessor :menu_items

  def self.menu menu=nil
    if menu
      self.menu_items.merge! menu
    else
      self.menu_items
    end
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.json { respond_with_bip(resource) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(resource) }
      end
    end
  end

  def current_ability
    controller_name_segments = params[:controller].split('/')
    controller_name_segments.pop
    controller_namespace = controller_name_segments.join('/').camelize
    @current_ability ||= Ability.new(current_user, { namespace: controller_namespace })
  end


end

app/controllers/adm/financials_controller.rb
class Adm::FinancialsController < Adm::BaseController
  require 'csv'
  inherit_resources
  defaults  resource_class: Project, collection_name: 'projects', instance_name: 'project'
  menu I18n.t("adm.financials.index.menu") => Rails.application.routes.url_helpers.adm_financials_path
  has_scope :by_permalink, :name_contains, :user_name_contains, :financial, :by_state, :by_progress
  has_scope :between_expires_at, using: [ :start_at, :ends_at ], allow_blank: true

  actions :index

  def projects
    @search = apply_scopes(Project).includes(:user).order("CASE state WHEN 'successful' THEN 1 WHEN 'waiting_funds' THEN 2 ELSE 3 END, (online_date + (online_days::text||' days')::interval)::date")
  end

  def collection
    @projects = projects.page(params[:page])
  end

  def index
    respond_to do |format|
      format.html {collection}
      format.csv do
        csv_string = CSV.generate do |csv|
          # header row
          csv << ["name", "moip", "goal", "reached", "moip_tax", "catarse_fee", "expires_at", "backer_report", "state"]
          # data rows
          projects.each do |project|
            catarse_fee = ::Configuration[:catarse_fee].to_f * project.pledged
            csv << [project.name,
                    project.user.moip_login,
                    project.display_goal,
                    "#{project.display_pledged} (#{project.progress}%)",
                    "#{view_context.number_to_currency project.backers.confirmed.sum('payment_service_fee'), unit: '$', precision: 2, delimiter: '.'}",
                    "#{view_context.number_to_currency catarse_fee, unit: '$', precision: 0, delimiter: '.' } (#{view_context.number_to_currency project.pledged - catarse_fee, unit: '$', precision: 0, delimiter: '.'})",
                     "#{project.display_expires_at} (#{I18n.l(8.weekdays_from(project.expires_at).to_date)})",
                     "#{adm_reports_backer_reports_url(project_id: project.id, format: :csv)}",
                     project.state
            ]
          end
        end
        send_data csv_string,
                  type: 'text/csv; charset=iso-8859-1; header=present',
                  disposition: "attachment; filename=financials.csv"
      end
    end
  end

end

app/controllers/adm/projects_controller.rb
class Adm::ProjectsController < Adm::BaseController
  menu I18n.t("adm.projects.index.menu") => Rails.application.routes.url_helpers.adm_projects_path

  has_scope :by_id, :pg_search, :user_name_contains, :by_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table, default: 'created_at'

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def collection
    @projects = end_of_association_chain.page(params[:page])
  end
end

app/controllers/adm/reports/backer_reports_controller.rb
class Adm::Reports::BackerReportsController < Adm::Reports::BaseController
  def end_of_association_chain
    super.where(project_id: params[:project_id])
  end
end

app/controllers/adm/reports/base_controller.rb
class Adm::Reports::BaseController < Adm::BaseController
  inherit_resources
  responders :csv
  respond_to :csv
  actions :index
end

app/controllers/adm/users_controller.rb
class Adm::UsersController < Adm::BaseController
  inherit_resources
  menu I18n.t("adm.users.index.menu") => Rails.application.routes.url_helpers.adm_users_path
  before_filter :set_title
  before_filter :set_totals

  has_scope :by_id, :by_name, :by_email, :by_payer_email, :by_key, :has_credits, :has_credits_difference, only: :index

  protected
  def set_totals
    totals = end_of_association_chain.backer_totals
    @total_users = totals[:users].to_i
    @total_backs = totals[:backs]
    @total_backed = totals[:backed]
    @total_credits = totals[:credits]
  end

  def set_title
    @title = t("adm.users.index.title")
  end

  def collection
    @users ||= end_of_association_chain.order_by(params[:order_by] || 'coalesce(user_totals.sum, 0) DESC').includes(:user_total).page(params[:page])
  end
end

app/controllers/backers_controller.rb
class BackersController < ApplicationController
  inherit_resources
  defaults resource_class: Backer, collection_name: 'backs', instance_name: 'back'
  belongs_to :user
  actions :index
  respond_to :json, only: [:index]

  def index
    index! do |format|
      format.json{ return render json: @backs.includes(:user, :reward, project: [:user, :category, :project_total]).to_json({include_project: true, can_manage: (can? :manage, @user)}) }
      format.html{ return render nothing: true, status: 404 }
    end
  end
  
  def request_refund
    back = Backer.find(params[:id])

    authorize! :request_refund, back

    if can?(:request_refund, back) && back.can_request_refund?
      back.request_refund!
      flash[:notice] = I18n.t('credits.index.refunded')      
    end

    redirect_to user_path(parent, anchor: 'credits')      
    # render json: {status: status, credits: current_user.reload.display_credits}
  end  

  protected
  def collection
    @backs = end_of_association_chain.avaiable_to_count.order("confirmed_at DESC")
    @backs = @backs.not_anonymous unless @user == current_user or (current_user and current_user.admin)
    @backs = @backs.page(params[:page]).per(10)
  end
end

app/controllers/channels/adm/projects_controller.rb
class Channels::Adm::ProjectsController < Adm::BaseController
  menu I18n.t('channels.adm.menu') => Rails.application.routes.url_helpers.adm_projects_path

  
  has_scope :by_id, :pg_search, :user_name_contains, :order_table, :by_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table do |controller, scope, value|
  value.present? ? scope.order_table(value) : scope.order('created_at DESC')
  end



  before_filter do
    @channel        =  Channel.find_by_permalink!(request.subdomain.to_s)
    @total_projects =  @channel.projects.size 
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project    = @channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
    def begin_of_association_chain
      @channel
    end

    def collection
      @projects = apply_scopes(@channel.projects.page(params[:page]))
    end
  

end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update_info, :review, :create
  skip_before_filter :force_http, only: [:create, :update_info]
  skip_before_filter :verify_authenticity_token, only: [:moip]
  load_and_authorize_resource
  belongs_to :project

  def update_info
    resource.update_attributes(params[:backer])
    render json: {message: 'updated'}
  end

  def index
    @backers = parent.backers.avaiable_to_count.order("confirmed_at DESC").page(params[:page]).per(10)
    render json: @backers.to_json(can_manage: can?(:update, @project))
  end

  def show
    @title = t('projects.backers.show.title')
    session[:thank_you_backer_id] = nil
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {host: ::Configuration[:secure_review_host], protocol: 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', name: @project.name)
    @backer = @project.backers.new(user: current_user)
    empty_reward = Reward.new(id: 0, minimum_value: 0, description: t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.reward_id = nil if params[:backer][:reward_id].to_s == '0'
    @backer.user = current_user
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      success.html do
        session[:thank_you_backer_id] = @backer.id      
        return render :create
      end
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed?
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end
end

app/views/adm/backers/index.html.slim
#page_content
  .container
    .title
      h1= t('.title')
      h2
        strong= "#{@total_backers} "
        = t('.total_backers')
        | ·
        strong= "#{@total_backs} "
        = t('.total_backs')
        | ·
        strong= "#{number_to_currency @total_backed, unit: '$', precision: 0, delimiter: '.'} "
        = t('.total_backed')
        | ·
        strong= "#{@total_users} "
        = t('.total_users')

    .filters
      .bootstrap-form
        = form_tag adm_backers_path, method: :get, class: 'form-horizontal' do |f|
          fieldset
            .input
              = label_tag :by_user_id, t('.user_id')
              = text_field_tag :by_user_id, params[:by_user_id], class: 'input-small'
            .input
              = label_tag :between_values, t('.between_values')
              = text_field_tag 'between_values[start_at]', (params[:between_values][:start_at] if params[:between_values].present?), class: 'input-small'
              | &nbsp;
              | &nbsp;
              = text_field_tag 'between_values[ends_at]', (params[:between_values][:ends_at] if params[:between_values].present?), class: 'input-small'
            .input
              = label_tag :by_state, t('.by_state')
              = select_tag :by_state, options_for_select(Backer.state_names, params[:by_state]), include_blank: true
            .input
              = label_tag :by_key, t('.key')
              = text_field_tag :by_key, params[:by_key]
            .input
              = label_tag :project_name_contains, t('.project')
              = text_field_tag :project_name_contains, params[:project_name_contains]
            .input
              = label_tag :user_name_contains, t('.user')
              = text_field_tag :user_name_contains, params[:user_name_contains]
            .bootstrap-twitter
              .input.submit
                = submit_tag t('.submit'), class: 'btn btn-success'
          fieldset
            .input.check
              = check_box_tag :confirmed, :on, params[:confirmed]
              = label_tag :confirmed, t('.confirmed')
            .input.check
              = check_box_tag :credits, :on, params[:credits]
              = label_tag :credits, t('.credits')

            .input.check
              = check_box_tag :pending_to_refund, :on, params[:pending_to_refund]
              = label_tag :pending_to_refund, t('.pending_to_refund')
            /.input.check
            /  = check_box_tag :requested_refund
            /  = label_tag :requested_refund, t('.requested_refund')
            /.input.check
            /  = check_box_tag :refunded
            /  = label_tag :refunded, t('.refunded')
            .input.total_results
              #total_results
                = pluralize_without_number collection.count, t('found_singular'), t('found_plural')
                strong= collection.count
                = pluralize_without_number(collection.count, t('backer_singular'), t('backer_plural')).downcase
      .clearfix
      = paginate @backers
      - if @backers.empty?
        = t('.no_backers')
      - else
        .bootstrap-twitter
          table.table.table-striped
            thead
              tr
                th= t('.info')
                th= t('.project')
                th= t('.user')
                th= t('.value')
                th= t('.reward')
                th= t('.key')
                th= t('.anonymous')
                th= t('.credits')
                th= t('.state')
                th
            tbody
              - @backers.includes(:project, :user, :reward).each do |backer|
                tr id=backer.id class=cycle("even", "odd")
                  td
                    .bootstrap-twitter
                      div id="backerInfo#{backer.id}" class="hide modal"
                        .modal-header
                          h3= t('.backer_info', key: backer.key)
                        .modal-body style='text-align: left'
                          p
                            strong= t('.payment_method')
                            | &nbsp;
                            = backer.payment_method
                          p
                            strong= t('.payment_id')
                            | &nbsp;
                            = backer.payment_id
                          p
                            strong= t('.payer_email')
                            | &nbsp;
                            = backer.payer_email
                          p
                            strong= t('.user_email')
                            | &nbsp;
                            = backer.user.email
                          p
                            strong= t('.payment_choice')
                            | &nbsp;
                            = backer.payment_choice
                          p
                            strong= t('.created_at')
                            | &nbsp;
                            = l(backer.created_at)

                        .modal-footer
                          button type='button' data-dismiss="modal" class="btn" OK
                    = link_to "#backerInfo#{backer.id}", class: 'btn btn-mini', data: {toggle:'modal'} do
                      i.icon-info-sign
                  td title=backer.project.name
                    = link_to project_by_slug_path(permalink: backer.project.permalink) do
                      = image_tag backer.project.display_image, class: 'project_img'
                  td title=backer.user.display_name
                    = link_to user_path(backer.user) do
                      = image_tag backer.user.display_image, class: 'user_img'
                    .user_id= best_in_place [:adm, backer], :user_id, method: :put, type: :input
                  td= best_in_place [:adm, backer], :value, method: :put, type: :input
                  td title=("#{backer.reward.display_minimum} - #{backer.reward.description}" if backer.reward)
                    - if backer.reward
                      = backer.reward.display_minimum
                    - else
                      | -
                    .btn-group
                      = link_to 'javascript:void(0);', data: {toggle: 'dropdown'}, class: 'btn btn-mini dropdown-toggle' do
                        span.caret
                      ul.dropdown-menu
                        li title=("#{t('.no_reward')}" ) = link_to t('.no_reward'), change_reward_adm_backer_path(backer, reward_id: nil), method: :put
                        - backer.available_rewards.each do |reward|
                          li title=("#{reward.display_minimum} - #{reward.description}" ) = link_to reward.minimum_value, change_reward_adm_backer_path(backer, reward_id: reward.id), method: :put

                  td.key= backer.key
                  td.checkbox= best_in_place [:adm, backer], :anonymous, method: :put, type: :checkbox, collection: [t('no'), t('yes')]
                  td= (backer.credits ? t('yes') : t('no'))
                  td= backer.state
                  td.bootstrap-twitter
                    .btn-group
                      = link_to 'javascript:void(0);', data: {toggle: 'dropdown'}, class: 'btn btn-mini dropdown-toggle' do
                        span.caret
                      ul.dropdown-menu
                        - if backer.confirmed?
                          li= link_to t('adm.backers.index.unconfirm_backer'), pendent_adm_backer_path(backer), method: :put
                        - else
                          li= link_to t('adm.backers.index.confirm_backer'), confirm_adm_backer_path(backer), method: :put
                        - if backer.requested_refund? or backer.confirmed?
                          li= link_to t('adm.backers.index.refund_backer'), refund_adm_backer_path(backer), method: :put
                        li= link_to t('adm.backers.index.refund_and_hide'), hide_adm_backer_path(backer), method: :put
                        li= link_to t('adm.backers.index.cancel'), cancel_adm_backer_path(backer), method: :put
      = paginate @backers
  .clearfix