config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  match '/thank_you' => "static#thank_you"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

# Comment this out when running rake db:migrate for the first time
  mount CatarseWepay::Engine => "/", as: "catarse_wepay"

  # Non production routes
  if Rails.env.development?
    resources :emails, only: [ :index ]
  end


  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/guidelines',            to: 'static#guidelines',          as: :guidelines
  get "/guidelines_tips",       to: "static#guidelines_tips",     as: :guidelines_tips
  get "/guidelines_backers",    to: "static#guidelines_backers",  as: :guidelines_backers
  get "/guidelines_start",      to: "static#guidelines_start",    as: :guidelines_start
  get "/referrals",             to: "static#referrals",           as: :referrals
  get "/foundation",            to: "static#foundation",          as: :foundation

  get "/about",                 to: "static#about",               as: :about
  get "/military",              to: "static#about_military",      as: :about_military
  get "/firefighters",          to: "static#about_firefighters",  as: :about_firefighters
  get "/first_responders",      to: "static#about_first_responders",as: :about_first_responders
  get "/community",             to: "static#about_community",      as: :about_community
  get "/entrepreneurial",       to: "static#about_entrepreneurial",as: :about_entrepreneurial
  get "/creative",              to: "static#about_creative",       as: :about_creative

  get "/departments",           to: "static#about_departments",    as: :about_departments
  get "/organizations",         to: "static#about_organizations",  as: :about_organizations
  get "/families",              to: "static#about_families",       as: :about_families

  match "/explore" => "explore#index", as: :explore
  match "/explore#:quick" => "explore#index", as: :explore_quick
  match "/credits" => "credits#index", as: :credits

  match "/reward/:id" => "rewards#show", as: :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ] do
      member do
        post 'sort'
      end
    end
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'video'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, only: [:index] do
      member do
        match :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end
  # match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/mudancadelogin" => "users#set_email", as: :set_email_users
  match "/:permalink" => "projects#show", as: :project_by_slug

  # Root path
  root to: 'projects#index'

end

app/controllers/adm/projects_controller.rb
class Adm::ProjectsController < Adm::BaseController
  menu I18n.t("adm.projects.index.menu") => Rails.application.routes.url_helpers.adm_projects_path

  has_scope :by_id, :pg_search, :user_name_contains, :by_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table, default: 'created_at'

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def collection
    @projects = end_of_association_chain.page(params[:page])
  end
end

app/controllers/channels/adm/projects_controller.rb
class Channels::Adm::ProjectsController < Adm::BaseController
  menu I18n.t('channels.adm.menu') => Rails.application.routes.url_helpers.adm_projects_path

  
  has_scope :by_id, :pg_search, :user_name_contains, :order_table, :by_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table do |controller, scope, value|
  value.present? ? scope.order_table(value) : scope.order('created_at DESC')
  end



  before_filter do
    @channel        =  Channel.find_by_permalink!(request.subdomain.to_s)
    @total_projects =  @channel.projects.size 
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project    = @channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
    def begin_of_association_chain
      @channel
    end

    def collection
      @projects = apply_scopes(@channel.projects.page(params[:page]))
    end
  

end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  belongs_to :channel, finder: :find_by_permalink!, param: :profile_id


  # Inheriting from the original Projects controller
  # With one addition: we include the project into the current channel
  before_filter only: [:create] { params[:project][:channels] = [@channel] }
  after_filter only: [:create] { notify_trustees }

  prepend_before_filter{ params[:profile_id] = request.subdomain }




  # After a project submission through a channel, notify all channel's trustees
  protected
    def notify_trustees

    end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update_info, :review, :create
  skip_before_filter :force_http, only: [:create, :update_info]
  skip_before_filter :verify_authenticity_token, only: [:moip]
  load_and_authorize_resource
  belongs_to :project

  def update_info
    resource.update_attributes(params[:backer])
    render json: {message: 'updated'}
  end

  def index
    @backers = parent.backers.avaiable_to_count.order("confirmed_at DESC").page(params[:page]).per(10)
    render json: @backers.to_json(can_manage: can?(:update, @project))
  end

  def show
    @title = t('projects.backers.show.title')
    session[:thank_you_backer_id] = nil
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {host: ::Configuration[:secure_review_host], protocol: 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', name: @project.name)
    @backer = @project.backers.new(user: current_user)
    empty_reward = Reward.new(id: 0, minimum_value: 0, description: t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.reward_id = nil if params[:backer][:reward_id].to_s == '0'
    @backer.user = current_user
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      success.html do
        session[:thank_you_backer_id] = @backer.id      
        return render :create
      end
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed?
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper
  load_and_authorize_resource only: [ :new, :create, :update, :destroy ]

  inherit_resources
  has_scope :pg_search, :by_category_id, :recent, :expiring, :successful, :recommended, :not_expired
  respond_to :html, except: [:backers]
  respond_to :json, only: [:index, :show, :backers, :update]
  skip_before_filter :detect_locale, only: [:backers]

  def index
    index! do |format|
      format.html do
        @title = t("site.title")
        collection_projects = Project.recommended_for_home
        unless collection_projects.empty?
          if current_user and current_user.recommended_projects
            @recommended_projects  ||= current_user.recommended_projects
            collection_projects   ||= collection_projects.where("id != ? AND category_id != ?",
                                                                current_user.recommended_projects.last.id,
                                                                @recommended_projects.last.category_id)
          end
          @first_project, @second_project, @third_project, @fourth_project = collection_projects.all
        end

        project_ids = collection_projects.map{|p| p.id }
        project_ids << @recommended_projects.last.id if (@recommended_projects && @recommended_projects.last && @recommended_projects.last.id)

        @expiring = Project.expiring_for_home(project_ids)
        @recent   = Project.recent_for_home(project_ids)
        @blog_posts = blog_posts
      end

      format.json do
        @projects = apply_scopes(Project).visible.order_for_search
        respond_with(@projects.includes(:project_total, :user, :category).page(params[:page]).per(6))
      end
    end
  end

  def new
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end

  def create
    @project = current_user.projects.new(params[:project])

    create!(notice: t('projects.create.success')) do |success, failure|
      success.html{ return redirect_to project_by_slug_path(@project.permalink) }
    end
  end

  def update
    params['project']['online_days'] = @project.number_online_days(params['project']['expires_at']) if params['project']['expires_at']
    update! do |success, failure|
      success.html{ return redirect_to project_by_slug_path(@project.permalink, anchor: 'edit') }
      failure.html{ return redirect_to project_by_slug_path(@project.permalink, anchor: 'edit') }
    end
  end

  def show
    begin
      if params[:permalink].present?
        @project = Project.where("lower(permalink) = ?", params[:permalink].downcase).last
      else
        return redirect_to project_by_slug_path(resource.permalink)
      end

      show!{
        @title = @project.name
        @rewards = @project.rewards.includes(:project).rank(:row_order).all
        @backers = @project.backers.confirmed.limit(12).order("confirmed_at DESC").all
        fb_admins_add(@project.user.facebook_id) if @project.user.facebook_id
        @update = @project.updates.where(id: params[:update_id]).first if params[:update_id].present?
      }
    rescue ActiveRecord::RecordNotFound
      return render_404
    end
  end

  def video
    project = Project.new(video_url: params[:url])
    if project.video
      render json: project.video.to_json
    else
      render json: {video_id: false}.to_json
    end
  end

  def check_slug
    project = Project.where("lower(permalink) = ?", params[:permalink].downcase)
    render json: {available: project.empty?}.to_json
  end

  def embed
    @project = Project.find params[:id]
    @title = @project.name
    render layout: 'embed'
  end

  def video_embed
    @project = Project.find params[:id]
    @title = @project.name
    render layout: 'embed'
  end

  def blog_posts
    Blog.fetch_last_posts.inject([]) do |total,item|
      total << item if total.size < 2
      total
    end
  rescue
    []
  end

  # Just to fix a minor bug,
  # when user submit the project without some rewards.
  def validate_rewards_attributes
    rewards = params[:project][:rewards_attributes]
    rewards.each do |r|
      rewards.delete(r[0]) unless Reward.new(r[1]).valid?
    end
  end
end

app/views/projects/_banner_bottom.html.slim
.project-categories-banner.row
  .title.large-8.large-centered.columns
    h2 Great Ways To Raise Money For Your Cause
    h4 Create your own fundraiser or join and existing fundraising team, which is right for you?
    .circle-icon

  section.categories.large-8.large-centered.columns
    .community.large-4.large-uncentered.small-8.columns.small-centered
      article
        h3 Support Organizations
        .line-break
        p
          | Increase your fundraising efforts, share your organization’s values &amp; promote your cause
        = link_to "LEARN MORE", about_organizations_path

    .entrepreneurial.large-4.large-uncentered.small-8.columns.small-centered
      article
        h3 First Responder Departments
        .line-break
        p
          | Raise funds for equipment, outreach programs &amp; engage with your community
        = link_to "LEARN MORE", about_departments_path

    .personal-creative.large-4.large-uncentered.small-8.columns.small-centered
      article
        h3 Individuals & Families
        .line-break
        p
          | Raise money for yourself, a friend or loved one during life's important moments
        = link_to "LEARN MORE", about_families_path

app/views/projects/_project.html.slim
div class="curated_project #{(defined?(has_comments) ? :compost_project : '')}"
  = render 'projects/box', project: project, custom_class: (custom_class if defined?(custom_class))
  - if defined?(has_comments)
    .project_comment
      h3= "#{(defined?(comments_title) ? comments_title : project.category)}"
      p= "#{project.home_page_comment}"
  - if defined?(project_curated_page) and project_curated_page.count > 0 and project_curated_page.first.description.present?
    .project_curator_description
      == project_curated_page.first.description_html

app/views/projects/_project_edit.html.slim
.bootstrap-form
  = semantic_form_for @project do |form|
    = form.inputs do
      - if current_user.admin
        = form.input :expires_at, as: :string
        = form.input :user_id
        = form.input :permalink, as: :string
      - if can? :update, @project, :name
        = form.input :name, as: :string, required: false
      - if can? :update, @project, :headline
        = form.input :headline, as: :string, required: false
      - if can? :update, @project, :category
        = form.input :category, as: :select, required: false
      - if can? :update, @project, :video_url
        = form.input :video_url, as: :string, hint: t('formtastic.hints.project.video_url_edit'),required: false
      - if can? :update, @project, :uploaded_image
        = form.input :uploaded_image, as: :file, required: false,
          hint: (@project.uploaded_image.present? ? image_tag(@project.uploaded_image.project_thumb.url, size: '220x172') : t('formtastic.hints.project.uploaded_image') )
      - if can? :update, @project, :online_days
        = form.input :online_days, as: :number, required: false
      - if can? :update, @project, :goal
        = form.input :goal, as: :number, required: false
      - if can? :update, @project, :about
        = form.label :about, t('formtastic.labels.project.about')
        = render 'project_wysihtml5'
        = form.text_area :about, required: false
        .tips
          h3 Formatting Tips
          = image_tag "catarse/icon_media.png"
          p If you paste the url of an image or a video from Youtube or Vimeo, they will appear in the description of the idea. Try it!
          = image_tag "catarse/icon_url.png"
          p When you paste a url any, it will become a link. For example, http://www.google.com becomes <a href="http://www.google.com">http://www.google.com</a>
          = image_tag "catarse/icon_linktext.png"
          p If you want to put text in link, simply use the following format: "text you want":http://google.com. For example, that example will turn into <a href="http://www.google.com">text you want</a>.
          = image_tag "catarse/icon_bold.png"
          p
            | You can use bold by adding two asterisks (**) before and after the text you want to format. For example, **bold text** will appear as <b>bold text</b>
          = image_tag "catarse/icon_italic.png"
          p
            |You can use italic by adding an underscore (_) before and after the text you want to format. For example, _my text_ text will appear as <i>my text</i>
      .clearfix
      .form-actions.bootstrap-twitter
        = form.submit class: 'btn'

app/views/projects/_project_rewards.html.slim
- @rewards.each do |reward|

  div[id="reward_#{reward.id}" data-update_url="#{sort_project_reward_path(@project, reward)}" class="box #{(can?(:update, reward) ? 'clickable_owner sortable' : '')} #{(@project.online? && !reward.sold_out? && !can?(:update, reward)  ? 'clickable'  : '' )}"]
    - if can?(:update, @project)
      .hide id="reward#{reward.id}Editor"
        .bootstrap-form
          = semantic_form_for [@project, reward] do |f|
            - if can? :update, reward, :minimum_value
              = f.input :minimum_value
            - if can? :update, reward, :description
              = f.input :description
            - if can? :update, reward, :maximum_backers
              = f.input :maximum_backers
            .bootstrap-twitter
              = f.submit class: 'btn'

            .clearfix.bootstrap-twitter
              = link_to [@project, reward], class: 'btn btn-danger', method: :delete, confirm: 'Are you sure?' do
                i.icon-trash.icon-white
      - if can?(:update, reward)
        .bootstrap-twitter
          = link_to "#reward#{reward.id}Editor", class: 'edit_reward btn btn-mini pull-right btn-primary' do
            i.icon-pencil.icon-white


    = hidden_field_tag 'url', "#{new_project_backer_path(@project)}/?reward_id=#{reward.id}"
    .top_reward
      - if reward.sold_out?
        span.icon.sold_out
      - else
        span.icon.avaliable
      h2= t('projects.rewards.reward_title', minimum: reward.display_minimum).html_safe
    em= pluralize(reward.backers.confirmed.count, t('backer_pledged_singular'), t('backer_pledged_plural'))
    .clearfix
    h5 DESCRIPTION
    p
      = reward.display_description
    - if reward.maximum_backers
      .maximum_backers.clearfix
        - if reward.sold_out?
          .sold_out= t('reward.sold_out')
        - else
          .limited= t('reward.limited')
          .remaining
            = reward.display_remaining
      - in_time_to_confirm = reward.backers.in_time_to_confirm.count
      - if in_time_to_confirm > 0
        .maximum_backers.in_time_to_confirm.clearfix
          .pending= t('projects.rewards.backs_to_confirm', count: in_time_to_confirm)
      .clearfix
    - if current_user && current_user.admin
      div class="reward_updated_at"
        p= "Modified on: #{I18n.l(reward.updated_at.to_date)} #{@project.online_date.nil? ? '' : ((@project.online_date > reward.updated_at)? '(draft)' : '(online)')}"
      - if reward.has_modification?
        div class="description_version rewardVersioning#{reward.id}"
          p= reward.last_description
        .maximum_backers.in_time_to_confirm.clearfix
          .updated_reward
            span id="rewardVersioning#{reward.id}"
              = "See previous version"
.clearfix

app/views/projects/_recommended_header.html.slim
#recommended_header
  .resume_about
    = image_tag "catarse/box_#{I18n.locale}.jpg"
    .bootstrap-form
      = form_tag(guidelines_path, method: :get, id: 'guidelines_form') do
        fieldset
          .bootstrap-twitter
            .button
              = link_to t('.guidelines'), guidelines_path, class:'btn_explore'
              span = t('.guidelines_subtitle')
  .project_info
    - if current_user
      - if @recommended_projects
        = render partial: "project_header", locals: {title: t('projects.recommended_header.suggest_for_you'), project: @recommended_projects.last} if @recommended_projects
      - else
        = render partial: "project_header", locals: {title: t('projects.recommended_header.highlight_project'), project: @fourth_project} if @fourth_project
    - else
      = render partial: "project_header", locals: {title: t('projects.recommended_header.highlight_project'), project: @fourth_project} if @fourth_project
  .clearfix

app/views/projects/index.html.slim
= content_for :title, t('site.title.index')
= content_for :description, t('site.description.index')
= render partial: 'banner'

#index_main_content.row
  .selected_projects.large-8.large-centered.columns
    .title.row
      h2.large-5.small-12.columns
          | Featured
          span.accented
            |  Projects
      = link_to t('main.links.selected'), explore_path(anchor: :recommended), class: "explore-more large-5 small-12"
    .projects.row
      = render partial: 'project', locals: {project: @first_project, custom_class: 'large-4 small-6 columns' } if @first_project
      = render partial: 'project', locals: {project: @second_project, custom_class: 'large-4 small-6 columns' } if @second_project
      = render partial: 'project', locals: {project: @third_project, custom_class: 'large-4 small-6 columns' } if @third_project
      = render partial: 'project', locals: {project: @fourth_project, custom_class: 'large-4 small-6 columns' } if @fourth_project

  .expiring_projects.large-8.large-centered.columns
    .title.row
      .title.large-12.small-12.columns
        h2.large-5.small-12.columns
          | Expiring
          span.accented
            |  Projects
        = link_to t('main.links.expiring'), explore_path(anchor: :expiring), class: "explore-more large-5 small-12"
    .projects.row
      - @expiring.each_with_index do |item,i|
        == render 'project', project: item, custom_class: 'large-4 small-6 columns'

  .recents_projects.large-8.large-centered.columns
    .title.row
      .title.large-12.small-12.columns
        h2.large-5.small-12.columns
          | Recent
          span.accented
            |  Projects
        = link_to t('main.links.recents'), explore_path(anchor: :recent), class: "explore-more large-5 small-12"
    .projects.row
      - @recent.each_with_index do |item,i|
        == render 'project', project: item, custom_class: 'large-4 small-6 columns'

= render partial: 'banner_bottom'

app/views/projects/show.html.slim
- content_for :js_templates do
  = render partial: 'backer'
  = render partial: 'project_templates'
  - if can?(:update, @project)
    = render partial: 'sort_rewards'

= content_for :meta_tags do
  - if @update
    meta name="description" content=@update.title
    meta property="og:title" content=@update.title
    meta property="og:description" content=@update.comment
    meta property="og:url" content=project_by_slug_url(@project.permalink, update_id: @update.id, locale: I18n.locale)
  - else
    meta name="description" content=@project.headline
    meta property="og:title" content=@project.name
    meta property="og:description" content=@project.headline
    meta property="og:url" content=project_by_slug_url(@project.permalink, locale: I18n.locale)
  meta property="og:type" content='cause'
  meta property="og:image" content=@project.display_image('project_thumb_facebook')
  meta property="og:site_name" content=::Configuration[:company_name]
  meta property="fb:admins" content="#{fb_admins}"

#top_title
  .container.grid-container
    #project_description[data-project=@project.to_json]
    .project_image.grid-25
      = image_tag @project.display_image('project_thumb')
    .section_header.grid-75
      h1= @project.name
      #lower_half_title
        .container
          h4= t('projects.project_header.without_city', category_name: link_to(@project.category, explore_path(anchor: @project.category.to_s.parameterize)), author: link_to(@project.user.display_name, user_path(@project.user))).html_safe

#page_content
  .container.grid-container
    - if @project.draft?
      .bottom-margin
        = render "draft_warning"

    - if @project.rejected?
      .bottom-margin
        = render "rejected_warning"

    - if @project.online? && can?(:update, @project)
      .bottom-margin
        = render "online_warning"

    - if @project.waiting_funds? && can?(:update, @project)
      .bottom-margin
        = render "waiting_funds_warning"

    - if @project.successful? && can?(:update, @project)
      .bottom-margin
        = render "successful_warning"

    - if @project.failed? && can?(:update, @project)
      .bottom-margin
        = render "failed_warning"
    .tab_container.grid-100
      nav#project_menu
        = link_to '#about', id: 'about_link', class: 'selected' do
          = t('.menu.about')
        = link_to '#updates', id: 'updates_link' do
          = t('.menu.updates')
          span.count=" (#{@project.updates.count})"
        = link_to '#backers', id: 'backers_link' do
          = t('.menu.backers')
          span.count=" (#{@project.total_backers})"
        = link_to '#comments', id: 'comments_link' do
          = t('.menu.comments')
          | &nbsp; (
          fb:comments-count href="#{request.url}"
          | )
        - if can? :update, @project
          = link_to '#edit', id: 'edit_link' do
            = t('.menu.edit')
          = link_to '#reports', id: 'reports_link' do
            = t('.menu.reports')
    .main#project-show.grid-70
      #project_content
        - if can? :update, @project
          #project_reports.content.hide= render 'project_reports'
          #project_edit.content.hide= render 'project_edit'

        #project_updates.content.hide= render 'project_updates'
        .media_content_backers
          #project_backers.content.hide
        #project_comments.content.hide= render 'comments'
        #project_about.content= render 'project_about'

        .clearfix
        #loading= image_tag "loading.gif"
      .clearfix
    .sidebar.grid-30.no-grid-padding
      .info
        #statistics
          .statistics
            .item.backers
              p= @project.total_backers
              strong= t('statistics.backers.subtitle')
            .item.goal
              p= @project.display_pledged
              strong= t('statistics.goal.subtitle', total: @project.display_goal).html_safe
            .item.time
              - if @project.draft? || @project.rejected?
                p= @project.online_days
                strong #{@project.online_days} #{pluralize_without_number(@project.online_days, I18n.t('datetime.prompts.day').downcase)} #{pluralize_without_number(@project.online_days, t('remaining_singular'), t('remaining_plural'))}
              - else
                p= @project.remaining_days
                strong #{@project.time_to_go[:unit].capitalize} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}
            .item.progress
              .status_bar
                .progress style="width: #{@project.display_progress}%;"
              h5= "#{@project.display_progress}%"
          - if @project.online? && @project.in_time?
            #pledge
              = form_tag(new_project_backer_path(@project), method: :get, id: 'back_project_form') do
                fieldset
                  = submit_tag t('projects.back_project.submit'), disabled: (not @project.online?)

        .share-buttons
          div class="share-twitter" data-url="#{(defined?(url) ? url : request.url)}" data-text="#{t('projects.twitter.take_a_look', :name => @project.name)}" data-title="Tweet"
          div class="share-facebook" data-url="#{(defined?(url) ? url : request.url)}" data-text="#{t('projects.twitter.take_a_look', :name => @project.name)}" data-title="Like"
          div class="share-googleplus" data-url="#{(defined?(url) ? url : request.url)}" data-text="#{t('projects.twitter.take_a_look', :name => @project.name)}" data-title="+1"

        #creator_profile
          h3= t('project_by')
          .avatar = @project.user.display_image_html width: 80, height: 80
          .personal_info
            p.name
             = link_to @project.user.display_name, user_path(@project.user)
            #bio
              p= @project.user.bio
          #city
            p.backer= t('count_backed_projects', total: @project.user.total_backs)
            p.city
              | #{@project.user.address_city}
        .user_social
          ul
            - if @project.user.facebook_link
              li
                = link_to "Perfil no facebook", @project.user.facebook_link, target: '_blank', class: 'facebook'
            - if @project.user.twitter
              li
                = link_to "Perfil no twitter", @project.user.twitter_link, target: '_blank', class: 'twitter'
            - if @project.user.email
              li
                = mail_to @project.user.email, @project.user.email, target: '_blank', class: 'email'
            - if @project.user.other_link
              li.other
                = link_to @project.user.other_link, @project.user.other_link, target: '_blank'

        .clearfix
        - if can?(:update, @project)
          .bootstrap-twitter.bootstrap-form
            .alert.alert-info
              h4.alert-header= t('.no_rewards_warning_title')
              p style="margin:0; padding:0;"
                = t('.no_rewards_warning')
            .clearfix
            = link_to t('.menu.add_reward'), 'javascript:void(0);', class: 'btn btn-success pull-right add_new_reward'
            .clearfix
            .well.new_reward_content.hide
              = semantic_form_for [@project, Reward.new] do |f|
                = f.input :minimum_value
                = f.input :description
                = f.input :maximum_backers
                = f.submit class: 'btn'
        #rewards= render 'project_rewards'

    .clearfix
= render 'show_embed'